name: ledgixerp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  fl_chart: ^1.2.0
  go_router: ^17.2.3
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  intl: ^0.20.2
  pdf: ^3.12.0
  printing: ^5.14.3
  excel: ^4.0.6
  csv: ^8.0.0
  file_picker: ^3.0.4
  path_provider: ^2.1.5
  share_plus: ^13.1.0
  firebase_storage: ^13.4.2
  image_picker: ^1.2.2
  flutter_colorpicker: ^1.1.0
  url_launcher: ^6.3.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/erp_logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#0F172A"
  image: assets/erp_logo.png
  android_12:
    image: assets/erp_logo.png
    color: "#0F172A"

flutter:
  uses-material-design: true
  assets:
    - assets/erp_logo.png
