// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA1-FoNcA7rit8PNbkE5q7JHpRvhtjCIw',
    appId: '1:486186946253:web:85cadec9730b3a0cf8a384',
    messagingSenderId: '486186946253',
    projectId: 'ledgix-erp',
    authDomain: 'ledgix-erp.firebaseapp.com',
    storageBucket: 'ledgix-erp.firebasestorage.app',
    measurementId: 'G-3FFNMGMT43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWxlSyJQP5m3fEuekfuggb_YLN0gu9i1Y',
    appId: '1:486186946253:android:90ed6f9520cac022f8a384',
    messagingSenderId: '486186946253',
    projectId: 'ledgix-erp',
    storageBucket: 'ledgix-erp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9dx8c6oZLNov7I7J7ARyH3Gjmjouyg-g',
    appId: '1:486186946253:ios:a1e115f2ea9a4f8af8a384',
    messagingSenderId: '486186946253',
    projectId: 'ledgix-erp',
    storageBucket: 'ledgix-erp.firebasestorage.app',
    iosBundleId: 'com.ledgix.erp.ledgixerp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9dx8c6oZLNov7I7J7ARyH3Gjmjouyg-g',
    appId: '1:486186946253:ios:a1e115f2ea9a4f8af8a384',
    messagingSenderId: '486186946253',
    projectId: 'ledgix-erp',
    storageBucket: 'ledgix-erp.firebasestorage.app',
    iosBundleId: 'com.ledgix.erp.ledgixerp',
  );
}
